config/routes.rb
SajovicMe::Application.routes.draw do

  
  resources :works

  resources :projects

  get "admin" => "admin#index", as: "admin"
  

  devise_for :users

  devise_scope :user do get "login" => "devise/sessions#new"
  end

  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs

  get "contact" => "domov#contact", :as => "contact_us"
  get "project" => "domov#projects", :as => "our_projects"
  get "blog" => "domov#blogs", :as => "blogs_articles"
  get "domov/index", as: "about"
  root "domov#index", as: "domov"

  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	validates :naslov, :opis, :presence => {:message => "mora biti izpolnjen!"}
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all.reverse
  end



  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blogs = Blog.all
  end


  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to admin_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:naslov, :opis)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <span class="round alert label"><li class="napaka"><%= msg %></li></span>
      <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <div class="row">
    <div class="large-8 columns">
      <div class="glava"><h6><%= f.label :naslov, placeholder: "Naslov", :required => true %></h6></div>
      <%= f.text_field :naslov %>
    </div>
  </div>

  <br>
        
  <div class="row">
    <div class="large-12 columns">
      <div class="glava">    
        <h6><%= f.label :opis %></h6></div>
            <%= f.text_area :opis, placeholder: "Polje za vnos", class: "ckeditor", :required => true %>
      </div>
    </div>
    <hr>  
    <div class="row">
      <div class="large-12 columns">
        <%= f.submit :Save!, class: "small button secondary" %>
        <%= link_to 'Admin panel', admin_path, class: "small button secondary" %>
        <%= link_to 'Back to blogs', blogs_path, class: "small button secondary" %>
      </div>   
    </div>
<% end %>  
</form>

app/views/blogs/edit.html.erb
<div class="glava">
	<h3>Uredi blog</h3>
</div>	

<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="glava">
  <h3>Lista vseh blogov</h3>
</div>
<table>
  <thead>
    <tr>
      <th width="300">Naslov</th>
      <th width="600">Opis</th>
      <th width="10">Prikaži</th>
      <th width="10">Urejaj</th>
      <th width="10">Izbriši</th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= truncate(strip_tags(blog.naslov), length: 15) %></td>
        <td><%= truncate(strip_tags(blog.opis), length: 40) %></td>
        <td><%= link_to 'Show', blog, class: "button secondary small" %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog), class: "button secondary small" %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure? You will lost data!' }, class: "button secondary small" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path, class: "button secondary small" %>

app/views/blogs/new.html.erb
<h3 class="glava">Nov blog</h3>

<%= render 'form' %>
<div class="row">
	<div class="large-12 columns">
		<%= link_to 'Home', domov_path, class: "small button secondary" %>
	</div>
</div>		

app/views/blogs/show.html.erb
<h6><%=h content_for(:title, @blog.naslov ) %></h6>


<div class="row">
	<div class="large-12 columns blog">
	<fieldset>
	<legend style="background-color:rgba(240, 240, 240, 0.0);"><p class="info-objava">Published on <%= @blog.created_at.strftime('%b %d, %Y') %><br>
	Article #<%=  @blog.id %></p></legend>
		<h6><strong><%= @blog.naslov %></strong></h6>
		<ul class="side-nav">
			<li class="divider"></li>
			<li><%= @blog.opis.html_safe %></li>
			<li class="divider"></li>
		</ul>	
			<p class="go_back">&#8629;<%= link_to 'Back', blogs_articles_path, class: "go_back" %></p>
		
	
	</fieldset>	
	</div>
</div>