config/routes.rb
SajovicMe::Application.routes.draw do

  
  resources :works

  resources :projects

  get "admin" => "admin#index", as: "admin"
  

  devise_for :users

  devise_scope :user do get "login" => "devise/sessions#new"
  end

  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs

  get "contact" => "domov#contact", :as => "contact_us"
  get "project" => "domov#projects", :as => "our_projects"
  get "blog" => "domov#blogs", :as => "blogs_articles"
  get "domov/index", as: "about"
  root "domov#index", as: "domov"

  

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:content)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 
<form>
  <div class="row">
    <div class="large-12 columns">
      <div class="glava">    
        <h6><%= f.label :referenca %></h6></div>
            <%= f.text_area :content, class: "ckeditor", :required => true %>
      </div>
    </div>
    <hr>  
    <div class="row">
      <div class="large-12 columns">
        <%= f.submit :Save!, class: "small button secondary" %>
        <%= link_to 'Admin panel', admin_path, class: "small button secondary" %>
      </div>   
    </div>
<% end %>  
</form>

app/views/projects/edit.html.erb
<div class="glava">
	<h3>Editing project</h3>
</div>
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="glava">
<h3>Listing projects</h3>
</div>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.content %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @project.content %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>