config/routes.rb
SajovicMe::Application.routes.draw do

  
  resources :works

  resources :projects

  get "admin" => "admin#index", as: "admin"
  

  devise_for :users

  devise_scope :user do get "login" => "devise/sessions#new"
  end

  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs

  get "contact" => "domov#contact", :as => "contact_us"
  get "project" => "domov#projects", :as => "our_projects"
  get "blog" => "domov#blogs", :as => "blogs_articles"
  get "domov/index", as: "about"
  root "domov#index", as: "domov"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Blaz Sajovic / Ruby On Rails Developer" %></title>
    <link rel="shortcut icon" href="/assets/bs_logo.png" />
  	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>


    <%= csrf_meta_tags %>
    <!-- Start of Woopra Code -->

<script>

(function(){

    var t,i,e,n=window,o=document,a=arguments,s="script",r=["config","track","identify","visit","push","call"],c=function(){var t,i=this;for(i._e=[],t=0;r.length>t;t++)(function(t){i[t]=function(){return i._e.push([t].concat(Array.prototype.slice.call(arguments,0))),i}})(r[t])};for(n._w=n._w||{},t=0;a.length>t;t++)n._w[a[t]]=n[a[t]]=n[a[t]]||new c;i=o.createElement(s),i.async=1,i.src="//static.woopra.com/js/w.js",e=o.getElementsByTagName(s)[0],e.parentNode.insertBefore(i,e)

})("woopra");

 

woopra.config({

    domain: 'sajovic.me'

});

woopra.track();

</script>

<!-- End of Woopra Code -->

    
  </head>

  <body>
  

  <nav class="top-bar">
    <% if user_signed_in? %>
    <ul class="title-area">
      
      <li class="divider"></li>
      <li class="name"></li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>  
    </ul>

    <section class="top-bar-section">
      <ul>
        <li class="divider"></li>
        <li><%= link_to "Dashboard", admin_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <li class="divider"></li>
        
      </ul> 
    </section>
   <% else %>    
<% end %>
  </nav>
<% if user_signed_in? %> 
  <div class="row">
    <div class="large-3 large-offset-1 columns  admin-area">
      <span class="radius secondary label welcome">Welcome Back <span class="ime">Blaž</span><span class="smejko"> :-)</span></span>  
  <% else %>
<% end %>    
    </div>
  </div> 

  <div class="row">



    <div class="large-3 small-7 columns">
      <div class="logo">
        <img src="<%= asset_path 'assets/bs_logo.png' %>" alt="Blaz Sajovic logo">
      </div>
      <div class="large-3 small-4 columns">
  
        <ul class="side-nav menu">
          <li class="divider"></li>
          <li><%= link_to_unless_current "About me", domov_path %></li>
          <li class="divider"></li>
          <li><%= link_to_unless_current "Blogs", blogs_articles_path %></li>
          <li class="divider"></li>
          <li><%= link_to_unless_current "My Projects", our_projects_path %></li>
          <li class="divider"></li>
          <li><%= link_to_unless_current "Contact Me", contact_us_path %></li>
          <li class="divider"></li>
        </ul> 
    
        <div class="quotes">
          <h6>Quotes</h6>
        <div class="all_quotes">  
          <h5>The hacker mindset doesn't actually see what happens on the other side, to the victim.</h5>
          <hr>
          <h4>Kevin Mitnick</h4>
        </div>  
        <div class="all_quotes">  
          <h5>“Measuring programming progress by lines of code is like measuring aircraft building progress by weight.”</h5>
          <hr>
          <h4>Bill Gates</h4>
        </div>
        <div class="all_quotes">  
          <h5>“First learn computer science and all the theory.  Next develop a programming style.  Then forget all that and just hack.”</h5>
          <hr>
          <h4>George Carrette</h4>
        </div>

        <div class="all_quotes">  
          <h5>I get hired by companies to hack into their systems and break into their physical facilities to find security holes. Our success rate is 100%; we've always found a hole.</h5>
          <hr>
          <h4>Kevin Mitnick</h4>
        </div>
        <div class="all_quotes">  
          <h5>“Microsoft has a new version out, Windows XP, which according to everybody is the ‘most reliable Windows ever.‘  To me, this is like saying that asparagus is ‘the most articulate vegetable ever.‘ “</h5>
          <hr>
          <h4>Dave Barry</h4>
        </div>      
        <div class="all_quotes">  
          <h5>“Software is like sex: It’s better when it’s free.”</h5>
          <hr>
          <h4>Steve McConnell</h4>
        </div>
      </div>  
    </div>
  </div>


  <div class="large-8 columns">
    <div class="row">
      <div class="large-4 large-offset-3 columns msg">
        <% flash.each do |name, msg| %>
        <span class="label"><%= content_tag :div, msg, id: "flash_#{name}" %></span>
        <% end %> 
      </div>
    </div>  
    <%= yield %>
  </div>

  
  <div class="large-1 small-3 columns social-show">
    <div class="fix">
    
      <ul class="social">
        <h1> Connect</h1>
        <li class="twitter"><p><%= link_to "Twitter", "https://twitter.com/RaDIrkA", :target => "_blank" %></p></li>
        <li class="facebook"><p><%= link_to "Facebook", "https://www.facebook.com/blaz.sajovic.3?ref=tn_tnmn", :target => "_blank" %></p></li>
        <li class="skype"><p><%= link_to "Skype", "skype://radirka8", :target => "_blank" %></p></li>
        <li class="github"><p><%= link_to "GitHub", "https://github.com/RaDIrkA", :target => "_blank" %></p></li>
        <li class="linkedin"><p><%= link_to "LinkedIn", "http://www.linkedin.com/pub/bla%C5%BE-sajovic/80/b39/25", :target => "_blank" %></p></li>
        <p class="zapri" title="Close">&#967;</p>
      </ul>
    </div> 
  </div>
  <p id="back-top"><a href="#top" title="Back to Top"><br/><br></a></p>
   

  </div>
  

 

<div class="footer">
  <div class="row">
    <div class="large-5 small-12 columns left-footer-nav">
      <ul class="inline-list">
        <li><%= link_to_unless_current "About me", domov_path %></li>
        <li><%= link_to_unless_current "Blogs", blogs_articles_path %></li>
        <li><%= link_to_unless_current "My Projects", our_projects_path %></li>                             <li><%= link_to_unless_current "Contact Me", contact_us_path %></li>
        <li style="margin:0 140px;"><%= link_to_unless_current "Admin", login_path %></li>
      </ul>
      <p>Copyright &copy; 2013 Blaz Sajovic, All rights reserved.<br>
       Innovative Web & Computers Services &raquo; <%= link_to "ProteusLab", "http://www.exemple.com", :target => "_blank" %></p>
       <br/>
    </div>

    <div class="large-2 columns" style="font-size:10px;text-align:center;">
      <br/><a rel="license" href="http://creativecommons.org/licenses/by/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/88x31.png" /></a><br />This work by <a xmlns:cc="http://creativecommons.org/ns#" href="sajovic.me" property="cc:attributionName" rel="cc:attributionURL">Blaz Sajovic</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 Unported License</a>.
    </div>




    <div class="large-5 small-12 columns right-footer-nav">
    <br/>
      <ul class="right-nav">
        <li>Powered by <%= link_to "Ruby on rails", "http://rubyonrails.org/", :target => "_blank" %></li>
        <li>Build on <%= link_to "Foundation", "http://foundation.zurb.com/", :target => "_blank" %> with my own customizations </li>
        <li>Deployed => <%= link_to "Heroku", "https://www.heroku.com/", :target => "_blank" %></li>
        <li>Git Repository => <%= link_to "GitHub", "https://github.com/", :target => "_blank" %></li>
        <li>Using most customizable editor => <%= link_to "CKEditor", "http://ckeditor.com/", :target => "_blank" %></li>      
      </ul>
    </div> 
      
  </div>
 </div>


        





  <%= javascript_include_tag "application" %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45114921-1', 'sajovic.me');
  ga('send', 'pageview');

</script>
  </body>
</html>